apiVersion: v1
kind: Service
metadata:
  name: svc-newsflash
  namespace: newsflash
spec:
  selector:
    app: newsflash
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080